### ISSUE TITLE
password of length 4 is missing uppercase

### ISSUE THREAD

**Issue by stefanheine** [xsellier/password-maker#4]
const passwordMaker = require('password-maker');
console.log(passwordMaker(4));

is generating passwords like 's-v6', '4#ok', 'q8+r', but none of them contains an uppercase character.

I would have expected that even such a short password contains a character of every class.

**Comment by xsellier** [comment]
Thank you @stefanheine.
I have just fixed, added unit test merged (see https://github.com/xsellier/password-maker/pull/5) and published a bugfix
